//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal InsuranceAmount { get; set; }
        public decimal TarrifRate { get; set; }
        public int InsuranceType_Id { get; set; }
    
        public virtual InsuranceType InsuranceType { get; set; }
    }
}
