//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab15
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public Nullable<int> degreeId { get; set; }
        public byte[] photo { get; set; }
    
        public virtual degree degree { get; set; }
    }
}
